@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MmIxNTA5NTQ3MzM4ZDg4Y2VjM2EzNDIiLCJpYXQiOjE2NTU4ODY2NjMsImV4cCI6MTY1NTg4NzI2MywidHlwZSI6IkFDQ0VTUyJ9.y8NjIryvdus1ZktEMbALmTtdAypVXpkE4JF0L9be_ok
@refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MmIxNTA5NTQ3MzM4ZDg4Y2VjM2EzNDIiLCJpYXQiOjE2NTU4MDI2ODAsImV4cCI6MTY1NTgwMzU4MCwidHlwZSI6IlJFRlJFU0gifQ.nmk_DnheG3jzsXE_SPLSiYjfoKw8PO_DTTgkB4zGiPI
@host=http://localhost:3000
@userId=62b1499e3bf639f1d3284dd4

POST {{host}}/v1/auth/register
Content-Type: application/json

{
    "username": "huynguyen",
    "email": "huynguyen91@gmail.com",
    "password": "huynguyen"
}


###
POST {{host}}/v1/auth/login
Content-Type: application/json

{
    "email": "huynguyen3@gmail.com",
    "password": "huynguyen"
}

###
POST {{host}}/v1/auth/logout
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}

###
POST {{host}}/v1/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}

###
POST {{host}}/v1/auth/forgot-password
Content-Type: application/json

{
    "email": "huynguyen3@gmail.com"
}

###
GET {{host}}/v1/users
Authorization: Bearer {{accessToken}}


###
POST {{host}}/v1/users
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "username": "tynguyen",
    "email": "tynguyen@gmail.com",
    "password": "tynguyen",
    "role": "user"
}

###
GET {{host}}/v1/users/{{userId}}
Authorization: Bearer {{accessToken}}


###
PATCH {{host}}/v1/users/{{userId}}
Authorization: Bearer {{accessToken}}

{
    "username": "tynguyen123",
    "email": "tynguyen123@gmail.com",
    "password": "tynguyen123"
}


###
DELETE {{host}}/v1/users/{{userId}}
Authorization: Bearer {{accessToken}}


