
POST http://localhost:3000/v1/auth/register
content-type: application/json

{
    "username": "huynguyen",
    "email": "huynguyen91@gmail.com",
    "password": "huynguyen"
}


###
POST http://localhost:3000/v1/auth/login
content-type: application/json

{
    "email": "huynguyen1111@gmail.com",
    "password": "huynguyen"
}

###
POST http://localhost:3000/v1/auth/logout
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MmIwMzg4MzA5MGZjMzU3ZDViZmVmMTYiLCJpYXQiOjE2NTU3NzU4MDMsImV4cCI6MTY1NTc3NjcwMywidHlwZSI6IlJFRlJFU0gifQ.GVEOEJJMwWt27ggKlfB757mqtA-bl7fWZRS5ynEExOc" 
}

###
GET http://localhost:3000/v1/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MmIxNDk5ZTNiZjYzOWYxZDMyODRkZDQiLCJpYXQiOjE2NTU3ODgzNTIsImV4cCI6MTY1NTc4ODk1MiwidHlwZSI6IkFDQ0VTUyJ9.1gOZ7Sy8OGIykIIj9I20OwI5s-q9JtH6I5vI3MAtI74

###
GET http://localhost:3000/v1/users/62b03883090fc357d5bfef16
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MmIxNDk5ZTNiZjYzOWYxZDMyODRkZDQiLCJpYXQiOjE2NTU3ODgzNTIsImV4cCI6MTY1NTc4ODk1MiwidHlwZSI6IkFDQ0VTUyJ9.1gOZ7Sy8OGIykIIj9I20OwI5s-q9JtH6I5vI3MAtI74